### ISSUE TITLE
Is and IsNot

### ISSUE THREAD

**Issue by lrweck** [stephenafamo/bob#1]
First of all, this looks really good, thanks for the package!

I was reading the code and I think the Is and IsNot funcs are swapped.
Is writes "IS DISTINCT FROM", which in simple terms means: is different, and IsNot: "IS NOT DISTINCT FROM", means essentially "is equal to" (of course respecting the null treatment). So, if I want to check that some "Is" something else, I should use "IS NOT DISTINCT FROM", and vice versa. It's a bit unintuitive, imo. What do you think?

**Comment by stephenafamo** [comment]
Nice catch. That is true.

Do you think it would be better to make the method names the full thing?

* `IsDistinctFrom()`
* `IsNotDistinctFrom()`

**Comment by lrweck** [comment]
Yeah, that makes sense. I'm on mobile, otherwise I'd make a PR.

**Comment by stephenafamo** [comment]
Done
