### ISSUE TITLE
Join Helpers FROM Clause Doesn't Use Alias (psql)

### ISSUE THREAD

**Issue by davidwarshaw** [stephenafamo/bob#112]
First, thanks for the great project!

When using join helpers with a schema-ed DB in version v0.20.5, it seems that the join FROM clause doesn't use an alias, but the ON clause does.
This:
```
	q := bobmodel.AJets(ctx, db,
		bobmodel.SelectJoins(ctx).AJets.InnerJoin.Pilot,
	)
	fmt.Println(q.MustBuild())
```
Gives me:
```
SELECT 
*
FROM "a"."jets" AS "a.jets"
INNER JOIN "a"."pilots" ON ("a.pilots"."pilotid" = "a.jets"."pilotid")
```
Which gives the error:
```
pq: missing FROM-clause entry for table "a.pilots"
```
It looks like the join helper should alias the table name, like so:
```
SELECT 
*
FROM "a"."jets" AS "a.jets"
INNER JOIN "a"."pilots" AS "a.pilots" ON ("a.pilots"."pilotid" = "a.jets"."pilotid")
```

**Comment by stephenafamo** [comment]
Looks like a bug. I'll find some time to fix it, if it is urgent for you, you can send in a PR and I'll review it.

**Comment by stephenafamo** [comment]
Check if #115 fixes this for you.
