### ISSUE TITLE
Unexpected query for psql.F() and As()

### ISSUE THREAD

**Issue by daddz** [stephenafamo/bob#121]
I'm not sure if this is intentional but the generated query was not what I expected.

Reproduction:
```go
psql.Select(
  sm.Columns(psql.F("min", "some_col").As("renamed"))
  sm.From("some_table"))
```

Result:
```sql
SELECT 
min(some_col)renamed 
FROM some_table
```

Expected:
```sql
SELECT 
min(some_col) AS renamed 
FROM some_table
```

What's the reason that no "AS" is being added?

**Comment by stephenafamo** [comment]
I'll have to investigate this. Thanks for reporting
