### ISSUE TITLE
Code generation generates code that does not compile

### ISSUE THREAD

**Issue by nicjohnson145** [stephenafamo/bob#13]
Given the following schema

```
mixer=# \d usr
                Table "public.usr"
  Column  | Type | Collation | Nullable | Default
----------+------+-----------+----------+---------
 username | text |           | not null |
 password | text |           | not null |
Indexes:
    "usr_pkey" PRIMARY KEY, btree (username)
Referenced by:
    TABLE "drink" CONSTRAINT "drink_username_fkey" FOREIGN KEY (username) REFERENCES usr(username) ON UPDATE CASCADE ON DELETE CASCADE

mixer=# \d drink
                                  Table "public.drink"
      Column       |  Type   | Collation | Nullable |              Default
-------------------+---------+-----------+----------+-----------------------------------
 id                | integer |           | not null | nextval('drink_id_seq'::regclass)
 name              | text    |           | not null |
 username          | text    |           | not null |
 primary_alcohol   | text    |           | not null |
 preferred_glass   | text    |           |          |
 ingredients       | text    |           | not null |
 instructions      | text    |           |          |
 notes             | text    |           |          |
 publicity         | integer |           | not null |
 under_development | boolean |           | not null |
 tags              | text    |           |          |
 favorite          | boolean |           | not null |
Indexes:
    "drink_name_username_key" UNIQUE CONSTRAINT, btree (name, username)
Foreign-key constraints:
    "drink_username_fkey" FOREIGN KEY (username) REFERENCES usr(username) ON UPDATE CASCADE ON DELETE CASCADE
```

bobgen config

```
❯ cat bobgen.yaml
psql:
  dsn: "postgres://mixer_usr:mixer_pass@localhost:5432/mixer?sslmode=disable"
  output: internal/storage/models
  wipe: true
```

and execution

```
go run github.com/stephenafamo/bob/gen/bobgen-psql@latest
```

Results in code generated in `usr.go` that is referencing types that don't exist in the `drink.go` file

```
❯ gotestsum# github.com/nicjohnson145/mixer/mixerserver/internal/storage/models
internal/storage/models/usr.go:284:88: undefined: DrinkSetter
internal/storage/models/usr.go:293:18: undefined: DrinksTable
internal/storage/models/usr.go:312:15: undefined: DrinksTable
internal/storage/models/usr.go:313:15: undefined: DrinkSetter
∅  config
∅  protos
                                                                                                                                                                                 
=== Errors
internal/storage/models/usr.go:284:88: undefined: DrinkSetter
internal/storage/models/usr.go:293:18: undefined: DrinksTable
internal/storage/models/usr.go:312:15: undefined: DrinksTable
internal/storage/models/usr.go:313:15: undefined: DrinkSetter
                                                                                                                                                                                 
DONE 0 tests, 4 errors in 0.147s
```

Not sure if I've configured something incorrectly, or I've exposed a bug

**Comment by nicjohnson145** [comment]
full repo structure available at https://github.com/nicjohnson145/mixer/tree/84c5dd77004f2c52e27680b0e95b9ecf8d742ca8

**Comment by stephenafamo** [comment]
The issue is that the `drink` table does not have a primary key.

Change this:

```sql
CREATE TABLE drink (
    id SERIAL,
    -- other columns
)
```

To this:

```sql
CREATE TABLE drink (
    id SERIAL PRIMARY KEY,
    -- other columns
)
```

**Comment by nicjohnson145** [comment]
Is there a requirement that every table has a primary key to use this library? In this specific case, that was just a miss on my part and I'll for sure add it. But in the general case that seems rather limiting IMO.

**Comment by stephenafamo** [comment]
I will try to document this better:

1. It is not a requirement for every table to have a primary key. Tables without a primary key are treated as **views**. That is, they can only be read from. This is because`Updates` and `Deletes` require a primary key to know what row to modify. `Inserts` also need a primary key in many cases so it is just always required.
2. The error you get comes from relations. When creating or modifying relations, primary keys are required by extension since those are `Insert` and `Update` operations respectively.  
Techincally, this shouldn't cause an error for reading relationships, so perhaps the generated code can be modified to only generate the code to read relationships. However this is not yet the case.

**Comment by nicjohnson145** [comment]
That makes sense. Technically a unique-not-null-index (a unique index composed only of columns that have a not null constraint) would be enough to satisfy any update/delete requirements, as that type of index is effectively a primary key. The fact that inserts require a PK is unfortunate. But I do sympathize with the complexity that supporting those use cases could introduce.

I think mentioning the requirements for writing in the docs would be a big help. Thank you for the support, you've got an awesome library here. I'm excited to make more use of it 😄

**Comment by stephenafamo** [comment]
Thanks for the kind words. 

I will see if I can drop the PK requirement for relationships. However, I don't think I will automatically do a fallback to `UNIQUE NOT NULL` since it would be easier for the user to use that as a PK on their end 😅

**Comment by stephenafamo** [comment]
@nicjohnson145 the need for primary keys on relationships has been dropped in `v0.18.2`

**Comment by nicjohnson145** [comment]
Awesome! I'll check it out.
