### ISSUE TITLE
Update Query with Setter broken in v0.23.0

### ISSUE THREAD

**Issue by daddz** [stephenafamo/bob#143]
I ran into an issue in the new release affecting update queries:

```go
fooSetter := &models.FooSetter{
  Name: omit.From("bar"),
}

foo, err := models.Foo.Update(ctx, db, fooSetter)
if err != nil {
  panic(err)
}
```

Will produce this error:
```
pq: syntax error at or near \"=\""
```

If I remember the logs correctly it is caused by the `SET` args being wrapped in brackets. 
```sql
-- pre 0.23.0
UPDATE "foo" SET "name" = $1 WHERE ("id" IN ($2))
-- with 0.23.0
UPDATE "foo" SET ("name" = $1) WHERE ("id" IN ($2))
```

I will check it again later and provide more details when I find time.

**Comment by stephenafamo** [comment]
Fixed and released on `v0.23.1`
