### ISSUE TITLE
Nullable foreign keys

### ISSUE THREAD

**Issue by MeanSquaredError** [stephenafamo/bob#15]
In gen/drivers/relationships.go on line 30 you have
```
			localNullable := allNullable(t1, fk.Columns...)
			fkNullableMap[fk.Name] = localNullable
```
`allNullable` checks if all columns of the (possibly compound) foreign key are nullable and returns the corresponding boolean value. So you treat the foreign key as nullable if all of its components are nullable.

However a (composite) foreign key is nullable if any of the participating fields is nullable and a if a given composite foreign key value contains null in one of its fields then the whole composite key value is essentially treated as null and it will not match any other value.

So shouldn't it really be `anyNullable` instead of `allNullable`, i.e. the key is nullable if any of its components is nullable ?

**Comment by stephenafamo** [comment]
In Bob, the primary purpose of knowing if a key is nullable is to know if we can delete the relation safely, and for this, we do need all keys to be nullable.

**Comment by MeanSquaredError** [comment]
Thank you for the clarification.

It seems that the `localNullable` is assigned to `RelSide.KeyNullable` but I was not able to find where `KeyNullable` is being used afterwards. Is it actually unused or am I missing something?

**Comment by stephenafamo** [comment]
You're correct. I haven't yet implemented code generation for removing relations. Right now, one still has to manually delete them.
