### ISSUE TITLE
Code generation broken on version 0.23.0

### ISSUE THREAD

**Issue by NamLH1310** [stephenafamo/bob#150]
Code generation is currently broken from version 0.23.0 afterward using bobgen-mysql

**Comment by stephenafamo** [comment]
Please share more details?

What's the schema like? What was wrong with the generated code?

**Comment by NamLH1310** [comment]
- The `TableNameSetter` didn't fully implement the `setter[T any]` interface

<img width="824" alt="image" src="https://github.com/stephenafamo/bob/assets/57991476/8b908020-734e-4d1f-ad60-57135ad701f4">



- The `TableNameSetter.Expressions` method return `[]bob.Expression` whereas the parameter of `um.Set` is `[]string`

<img width="689" alt="image" src="https://github.com/stephenafamo/bob/assets/57991476/2dd01e66-37da-4c76-98a4-a92927a71bff">

- We have a table called `ResourceQuotas` (this is to make the table name consistent), and apparently bob is confused about the singleton variable and the type name

<img width="689" alt="image" src="https://github.com/stephenafamo/bob/assets/57991476/bfadd948-0d74-49ed-8674-07454fb8724b">

**Comment by stephenafamo** [comment]
You should also update the version of `bob` in your `go.mod` file.

If you generated with the same version as your dependency, then everything should be implemented correctly. If you are still seeing errors, you may have to restart your Editor's LSP
