### ISSUE TITLE
[Examples issue] int does not implement bob.Expression

### ISSUE THREAD

**Issue by krispetkov** [stephenafamo/bob#155]
Hey @stephenafamo,

I was trying to start using the library and was following the examples provided in the documentation, but I stumbled on an issue. When I try the example from [here](https://bob.stephenafamo.com/docs/query-builder/building-queries#expressions), I'm getting the following error:

<img width="1642" alt="Screenshot 2024-01-15 at 18 22 27" src="https://github.com/stephenafamo/bob/assets/6774998/d14cc041-da29-4916-bdb2-d6a0faca9903">

**Comment by stephenafamo** [comment]
Thanks. Fixed in 47241c0
