### ISSUE TITLE
Problem with jaswdr/faker dependency causes generated bob factory_random_test.go to fail.

### ISSUE THREAD

**Issue by trentclowater** [stephenafamo/bob#164]
The new generated factory file `bobfactory_random_test.go` added in either `v0.24` or `0.25` will fail in the `TestRandom_int64`,  `TestRandom_int32` and `TestRandom_int16` functions when using `github.com/jaswdr/faker/v2` version 2.0.3, which was released yesterday.

Version 2.0.3 does not produce random values for `Int64()`, `Int32()`, `Int16()`. `Int64()` will only produce `math.MinInt` for all values, and `Int32()` and `Int16()` will only produce `0` values.

Version 2.0.2 is better, but has another problem where it does not generate negative values for `UInt()` or `UInt64()` (but does for all the other `IntXX` methods. I suspect this problem also affects 2.00 and 2.01, although I didn't check.

This is just an FYI on why people might be seeing failures from `bobfactory_random_test.go`.

**Comment by stephenafamo** [comment]
I see you already reported a bug in the faker package [here](https://github.com/jaswdr/faker/issues/164).

Thank you. I'll keep an eye on that issue and close this once that is fixed.

**Comment by stephenafamo** [comment]
I think generated tests can be good to catch issues with the generated code itself. You can imagine relying on the factory to actually generate random values for other tests and having to track down this issue.

At the same time, I understand that having generated code break CI may be undesirable, so I believe you can disable test generation by passing the `--no-tests` flag or by setting it to true in the configuration

**Comment by stephenafamo** [comment]
Fixed upstream in `faker/v2`
