### ISSUE TITLE
Invalid Code Generation with enum values containing symbols

### ISSUE THREAD

**Issue by stephenafamo** [stephenafamo/bob#181]
Since enum values are title-cased and appended to the enum name to get the enum variable name, an enum value containing symbols would lead to invalid generated code:

```sql
CREATE TYPE "healthapp"."blood_group_enum" AS ENUM ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-');
```

```
❯ go generate
   1278 bytes        psql/bob_enums.go
2024/02/13 21:41:19 singleton template output: failed to format template

   7
   8 	type HealthappBloodGroupEnum string
   9
  10 	// Enum values for HealthappBloodGroupEnum
  11 	const (
>>>> 	HealthappBloodGroupEnumA+ HealthappBloodGroupEnum = "A+"
  13 		HealthappBloodGroupEnumA- HealthappBloodGroupEnum = "A-"
  14 		HealthappBloodGroupEnumB+ HealthappBloodGroupEnum = "B+"
  15 		HealthappBloodGroupEnumB- HealthappBloodGroupEnum = "B-"
  16 		HealthappBloodGroupEnumAB+ HealthappBloodGroupEnum = "AB+"
  17 		HealthappBloodGroupEnumAB- HealthappBloodGroupEnum = "AB-"

:12:26: expected ';', found '+' (and 4 more errors)
exit status 1
generate.go:10: running "go": exit status 1
```

**Comment by rkrishnasanka** [comment]
@stephenafamo wouldn't a quick solution for this be either replacing english words `+ -> Plus` for all the special characters ?

If that works, and you can point me to where this needs to change, I can work on the PR.

**Comment by stephenafamo** [comment]
That would be a good solution. However, I can't yet find a way to do the "symbol -> name" lookup. That is the blocker.

**Comment by rkrishnasanka** [comment]
I can create a dictionary for this, though I'm unsure where in the codebase I need to be looking to create this.

**Comment by rkrishnasanka** [comment]
Agreed, that would be the best way to go about it. Only question for me is where does the enum generation happen ?

**Comment by stephenafamo** [comment]
The template that writes enums is `gen/templates/models/singleton/bob_enums.go.tpl`

However, it is up to each driver to construct the enum type and value and provide them in `DBInfo[T]`.

The Enum structure is defined [here](https://github.com/stephenafamo/bob/blob/v0.25.0/gen/drivers/interface.go#L52)

**Comment by stephenafamo** [comment]
@rkrishnasanka @safaci2000 check if #207 fixes your issues
