### ISSUE TITLE
In clause cannot take an existing array easily

### ISSUE THREAD

**Issue by RangelReale** [stephenafamo/bob#19]
I have an existing array that I want to send to `psql.X(...).In´, which takes a `vals ...any`. This array is, for example, `[]string`.

There's no way of sending this array to this method as a list besides converting the entire array to `[]any` with a for loop.

Maybe there could be a `InArray` method that allowed seding a single value that must be an array?

**Comment by stephenafamo** [comment]
The issue is that even if we add an `InArray` method, it will also need to be `[]any` since methods cannot be generic.

What I want to do is add an `Arr` generic function that will convert an existing slice to a slice of `[]any`. For example:

```go
var ints = []int{1,2,3,4,5,6,7,8,9}
psql.X("column").In(psql.Arr(ints...)...)
```

What do you think?

**Comment by RangelReale** [comment]
I think it should work well, maybe the parameter for `.Arr` don't need to be a vararg, it will always be an array (don't know if it is possible to require it using generics).

The only bad thing is that this will require a copy of all items, depending on the amount and on the time this may copy a lot of things...

**Comment by stephenafamo** [comment]
The reason why I prefer variadic arguments is that they're easier to use. If someone has a slice, it can just be spread with `...` and if they have a single value, they can use it plainly. 

On the other hand, if the function takes a slice, then if the user has individual values, they have to wrap it in `[]string{}` which can be tedious to write.

**Comment by stephenafamo** [comment]
I'm rethinking adding this. The function is rather simple and can be implemented rather easily

```go
func Arr[T any](vals ...T) []any {
	a := make([]any, len(vals))
	for i, v := range vals {
		a[i] = v
	}

	return a
}
```

I'll rather leave it out to avoid bloating this package.
