### ISSUE TITLE
Hosting 

### ISSUE THREAD

**Issue by gedw99** [stephenafamo/bob#205]
Fly.io has replicated hosting for Postgres and SQLite 

it’s free up to a certain level .

**Comment by gedw99** [comment]
https://fly.io/blog/free-postgres/

**Comment by gedw99** [comment]
https://fly.io/docs/litefs/

**Comment by gedw99** [comment]
https://github.com/athena-logistics/athena-backend/blob/main/.github/workflows/part_deploy.yml shows how to build the Container to Github Container Registry and then Deploy to Fly.io.

**Comment by stephenafamo** [comment]
I am not sure what this has to do with Bob.

**Comment by gedw99** [comment]
It’s to easily run and scale out and host bob .
