### ISSUE TITLE
v0.25 broken netip.Addr support

### ISSUE THREAD

**Issue by gstarikov** [stephenafamo/bob#210]
Hi. trying to migrate from v0.22.1 to 0.25 and:
 - factory test fail on netip_Addr test - `cannot handle unexported field at {netip.Addr}.addr`
 - fetching from db into netip_Addr fails too -  `unsupported Scan, storing driver.Value type string into type *netip.Addr`

how to reproduce:
1. take postgres 16.2
2. create table `create table n (addr inet  );`
3. and just `go run github.com/stephenafamo/bob/gen/bobgen-psql@v0.25.0`

and there will be errors:
1. factory test error
```
panic: cannot handle unexported field at {netip.Addr}.addr:
	"net/netip".Addr
consider using cmpopts.EquateComparable to compare comparable Go types

func TestRandom_netip_Addr(t *testing.T) {
	t.Parallel()

	seen := make([]netip.Addr, 10)
	for i := 0; i < 10; i++ {
		seen[i] = random[netip.Addr](nil)
		for j := 0; j < i; j++ {
			if cmp.Equal(seen[i], seen[j]) {
				t.Fatalf("random[netip.Addr]() returned the same value twice: %v", seen[i])
			}
		}
	}
}
```

2. unsupported Scan
```
Scan error on column index 0, name "addr": unsupported Scan, storing driver.Value type string into type *netip.Addr

rows, err := models.N.InsertMany(ctx, t.DB, n...)
```

**Comment by stephenafamo** [comment]
This should already be fixed in the current `main` branch and will be in the next release.

Try and confirm if it is now fixed, if it is not, please reopen the issue.

**Comment by gstarikov** [comment]
factory test issues is fixed, but scan issue still actual
