### ISSUE TITLE
Add MustCreate and MustCreateMany methods to Templates

### ISSUE THREAD

**Issue by pcriv** [stephenafamo/bob#223]
I think it would be useful to have these methods as extra methods for testing.
I could try to do a PR for this if you agree this is a good idea

**Comment by stephenafamo** [comment]
These would be nice.

Another set of methods I want to add is `CreateOrFail(tb *testing.TB)` and `CreateManyOrFail(tb *testing.TB)`. 
These should call `tb.Fatalf()` if there is an error. This is likely better than a panic.

Also, if you do send in a PR, kindly add some documentation for it 🙏🏾

**Comment by stephenafamo** [comment]
Implemented in #230
