### ISSUE TITLE
Type Error When Generating Code for "groups" Table

### ISSUE THREAD

**Issue by vovanwin** [stephenafamo/bob#250]
Hello,

I am encountering a type error when generating code for the following table:

 
```sql
 create table groups
(
    id        uuid   primary key
);
```
![image](https://github.com/user-attachments/assets/a751ff0e-50e4-48a5-9865-259fa79010ad)
I suspect the issue might be related to the Group function name in github.com/stephenafamo/bob/dialect/psql/starter.go. It seems there is a conflict due to the function name Group, which might be causing the type mismatch.

Thank you.

**Comment by stephenafamo** [comment]
This shouldn't be a problem since they are in different packages. I have also tried this locally and I have no errors.

Can you make sure the version of Bob you are using to generate the code is the same as the one required by your package?
