### ISSUE TITLE
Column name conflicts with built in method

### ISSUE THREAD

**Issue by AllanCochrane** [stephenafamo/bob#262]
I have a table in a MySQL database with a column named `build`:

    CREATE TABLE `t1` (`id` int unsigned NOT NULL AUTO_INCREMENT, `build` int DEFAULT NULL,PRIMARY KEY (`id`));

The generated code has a conflict in the generated `factory/t1.go` file between the `Build` field and the `Build()` method, used to construct a T1 model.

I cannot see a way to alias or rename the field so that Bob can work with this table.

**Comment by stephenafamo** [comment]
Documentation on aliasing: <https://bob.stephenafamo.com/docs/code-generation/configuration#aliases>
