### ISSUE TITLE
Expose mappings / setMapping to public API

### ISSUE THREAD

**Issue by hiendaovinh** [stephenafamo/bob#273]
Hi, I was trying to customize Upsert method of the Table and needed to use mappings.GetMappings.

I would be great if we can either expose `orm.Table.setMapping` or moving `internal/mappings` package out of internal.
Thanks a lot.

**Comment by stephenafamo** [comment]
I left these in `internal` so there is no burden of maintaining backwards compatibility.

Can you share more info about what type of customization you're doing to the `Upsert` method?

**Comment by hiendaovinh** [comment]
Yeah, I'm trying to have a `im.Where` with `DoUpdate` which is not available right now with model.UpsertMany

**Comment by hiendaovinh** [comment]
Sure, I will go with a builder like this
```go
q := psql.Insert(
	im.Into(bob.Cars.NameAs(ctx)),
	im.Returning(bob.Cars.Columns()),
	im.OnConflict([]any{bob.ColumnNames.Cars.UserID, bob.ColumnNames.Cars.Make}...).
		DoUpdate(
			im.Where(
				psql.Or(
					bob.ArticleColumns.Vin.IsNull(),
				),
			),
			im.SetExcluded([]string{
				bob.ColumnNames.Cars.Vin,
				bob.ColumnNames.Cars.Content,
				bob.ColumnNames.Cars.UpdatedAt,
			}...),
		),
)
```

Vin is nullable text. With these indexes
```
CREATE UNIQUE INDEX ON "cars"("user_id", "make");
CREATE UNIQUE INDEX ON "cars"("make", "vin");
```

**Comment by stephenafamo** [comment]
I have been thinking of this and I believe I have a great solution for the `Upsert` method.

This would be a breaking change and the signature of the method will change, but I think it is for the better.

**Comment by hiendaovinh** [comment]
Could you introduce the implementation in with non-breaking behavior like UpsertBeta?

**Comment by stephenafamo** [comment]
> Could you introduce the implementation in non-breaking behavior like UpsertBeta?

I could, but I probably won't.

Bob is still pre-1.0, so these breaking changes are expected. 

As a matter of fact in the process of working on this, I've gone down other rabbit holes so the next release may have several large breaking changes.

**Comment by hiendaovinh** [comment]
Sorry for wasting more of your time than needed :laughing:

**Comment by stephenafamo** [comment]
> Sorry for wasting more of your time than needed 😆

All worth it 😁

**Comment by stephenafamo** [comment]
See #291 for all the changes...

Its a big refactor and there are a number of breaking changes, especially to the Table methods.

For your case, the important bit is this (from the CHANGELOG):

- Removed `Insert/InsertMany/Upsert/UpsertMany` methods from `orm.Table` since they are not needed.  
  It is possible to do the same thing, with similar effor using the the `InsertQ` method (which is now renamed to `Insert`).

At the core of the changes is that you can now simply use Table queries like any other query and supply your Mods:

```go
setters := []*models.CarSetter{...}
cars, err := models.Cars.Insert(
        bob.ToMods(setters...),
	im.OnConflict([]any{bob.ColumnNames.Cars.UserID, bob.ColumnNames.Cars.Make}...).
		DoUpdate(
			im.Where(
				psql.Or(
					bob.CarColumns.Vin.IsNull(),
				),
			),
			im.SetExcluded([]string{
				bob.ColumnNames.Cars.Vin,
				bob.ColumnNames.Cars.Content,
				bob.ColumnNames.Cars.UpdatedAt,
			}...),
		),
).All(ctx, err)
```

**Comment by stephenafamo** [comment]
@hiendaovinh did you try out the changes? Any feedback?
