### ISSUE TITLE
Syntactically incorrect upsert and upsertMany queries

### ISSUE THREAD

**Issue by edlundin** [stephenafamo/bob#276]
Hi, I wanted to report that when using `Upsert` or `UpsertMany`, the generated PSQL query returns a syntax error. For context, the model is generated from a Prisma schema.

```go
prisma.Ecowatts.Upsert(ctx, client, true, []string{prisma.EcowattColumns.Date.String()}, nil, ecoWattValues[0])
```

generates

```sql
INSERT INTO "ecowatt" AS "ecowatt" ("id", "date", "color", "message", "details", "lastUpdate")
        VALUES (DEFAULT, $1, $2, $3, $4, DEFAULT)
        ON CONFLICT ("ecowatt"."date") DO UPDATE SET
        "date" = EXCLUDED. "date",
        "color" = EXCLUDED. "color",
        "message" = EXCLUDED. "message",
        "details" = EXCLUDED. "details"
        RETURNING "ecowatt"."id" AS "id", "ecowatt"."date" AS "date", "ecowatt"."color" AS "color", "ecowatt"."message" AS "message", "ecowatt"."details" AS "details", "ecowatt"."lastUpdate" AS "lastUpdate"
```

According to the [PSQL documentation](https://www.postgresql.org/docs/current/sql-insert.html), `ON CONFLICT ("ecowatt"."date") DO UPDATE SET` is not syntactically correct, but `ON CONFLICT "ecowatt"."date" DO UPDATE SET` (without parenthesis).

This issue is also true when using `UpsertMany`.

**Comment by stephenafamo** [comment]
My first guess is that the parentheses do not come from the `Upsert` itself, but from the `.String()` method of the columns. Try this instead:

```go
prisma.Ecowatts.Upsert(ctx, client, true, []string{prisma.ColumnNames.Ecowatt.Date}, nil, ecoWattValues[0])
```
