### ISSUE TITLE
Prisma driver seems to ignore bobgen.yaml

### ISSUE THREAD

**Issue by edlundin** [stephenafamo/bob#277]
Hi, this is my first time using the Prisma driver for Bob, so it is possible that the issue comes from me not using the bobgen.yaml correctly.

Currently, my `schema.prisma` containers the following generator:

```prisma
generator client-go {
    provider   = "go run github.com/stephenafamo/bob/gen/bobgen-prisma"
    configFile = "./bobgen.yaml"
}
```

And, in the same folder as the schema.prisma, a file `bobgen.yaml` is also located. And I know that Prisma sees the file because it gives an error otherwise.

```yaml
prisma:
  pkgname: prismago
tags:
  - json
no_factory: true
```

I already use the `no_factory` configuration with another project that uses Atlas, and it works as intended. However, with Prisma, the factory files are still generated. The Go package name also stays the default `prisma`.

Did I do something wrong in my configuration or is there a problem elsewhere ?

Thanks!

**Comment by stephenafamo** [comment]
Make sure that `wipe: true` is also set.

It may be that new factory files are not generated, but the existing ones are not deleted.

**Comment by edlundin** [comment]
Whether I add `wipe: true` or delete the generated folder, the behaviour stays the same.

**Comment by stephenafamo** [comment]
No matter how I try, I cannot replicate this issue. The factory is generated or excluded as expected on my end.

**Comment by edlundin** [comment]
For context, this go module is inside a NX monorepo, alongside an existing Prisma configuration. I cannot share the repo, though.

Is there a way to run the command in verbose mode, or something that could give some hints as to what is happening?

**Comment by stephenafamo** [comment]
Try running `DEBUG="*" prisma generate`
