### ISSUE TITLE
Chain From Mod

### ISSUE THREAD

**Issue by zibi94** [stephenafamo/bob#289]
Following PSQL documentation: https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-FROM
`The FROM clause derives a table from one or more other tables given in a comma-separated table reference list.`
```
FROM table_reference [, table_reference [, ...]]
```
There should be possibility to use more than one from mod.
But for now each next overwrite previous one.

As on the example:
```
func main() {
	qs, _ := psql.Select(
		sm.Columns("id", "name"),
		sm.From("users"),
		sm.From("clients"),
		sm.Where(psql.Quote("id").EQ(psql.Arg(100))),
	).MustBuild()

	fmt.Println(qs)
	// Out: SELECT id, name FROM clients WHERE ("id" = $1)
	// Expected: SELECT id, name FROM users, clients WHERE ("id" = $1)
}
```

Also there should be a possibility to chain from table and from query.
As on the example:
```
func main() {
	qs, _ := psql.Select(
		sm.Columns("id", "name", "type"),
		sm.From("users"),
		sm.From(psql.Select(
			sm.Columns("id", "type"),
			sm.From("clients"),
			sm.Where(psql.Quote("client_id").EQ(psql.Arg("123"))),
		)).As("clients"),
		sm.Where(psql.Quote("id").EQ(psql.Arg(100))),
	).MustBuild()

	fmt.Println(qs)
	// Out:
	// SELECT id, name, type
	// FROM (
	//   SELECT id, type
	//   FROM clients
	//   WHERE ("client_id" = $1)
	// ) AS "clients"
	// WHERE ("id" = $2)

	// Expected:
	// SELECT id, name, type
	// FROM users, (
	//   SELECT id, type
	//   FROM clients
	//   WHERE ("client_id" = $1)
	// ) AS "clients"
	// WHERE ("id" = $2)
}
```

**Comment by stephenafamo** [comment]
The documentation says: 

> If more than one table reference is listed in the FROM clause, the tables are cross-joined

Since there is a different (arguably clearer) way to achieve the same result, I chose to keep things simple. You can do this instead:

```go
	psql.Select(
		sm.Columns("id", "name", "type"),
		sm.From("users").As("u"),
		sm.CrossJoin(psql.Select(
			sm.Columns("id", "type"),
			sm.From("clients"),
			sm.Where(psql.Quote("client_id").EQ(psql.Arg("123"))),
		)),
		sm.Where(psql.Quote("id").EQ(psql.Arg(100))),
	)
```

Doing this, I realised that I left out the ability to add aliases to `CROSS JOIN`, and I'll add that soon.
