### ISSUE TITLE
Include CASE WHEN expression starter

### ISSUE THREAD

**Issue by TimurUtyaganov** [stephenafamo/bob#293]
I'm looking for a convenient way to use case when clause

**Comment by stephenafamo** [comment]
Can you give an example of the query you're trying to build?

**Comment by TimurUtyaganov** [comment]
> Can you give an example of the query you're trying to build?

select b.id, b.created_at from blocks b where case when b.type = 'periodic' then b.created_at - interval '10' day <= now() when b.type = 'test' then b.color in (...) end. 
Something like that. Thx for replying

**Comment by stephenafamo** [comment]
No expression helper for this yet.... I'll add this later

**Comment by k4n4ry** [comment]
@stephenafamo 
Hello, I'd like to help resolve this issue. Would you mind if I work on it?

**Comment by stephenafamo** [comment]
Sure. Go ahead.

My suggestion:

1. Since the `CASE` syntax is the same across all 3 dialects (Postgres, MySQL and SQLite), create a CASE expr in the `expr` package and then use it in `dialect/starters.go`
2. the base expression itself should return a "Chainable" mod that can be used to add `WHEN` and `END` clauses. 
    ```go
    expr.Case().                                             // should not yet be a valid expression
        When(condition bob.Expression, then bob.Expression). // can stop here and be a valid expression
        When(condition bob.Expression, then bob.Expression). // can stop here and be a valid expression
        Else(bob.Expression)                                 // can stop here and be valid
    ```
    Look for `JoinChain` for an example of something chainable, although that is used to build a `bob.Mod`
