### ISSUE TITLE
Generated Update method overriding Before/After Update hook

### ISSUE THREAD

**Issue by iggydv** [stephenafamo/bob#295]
Bob version
`github.com/stephenafamo/bob v0.28.1`

I'm running into an issue, which I'm not sure if it's a bug or a logic issue.

```golang
block, err := dbgen.Blocks.Query(ctx, db, dbgen.SelectWhere.Blocks.Key.EQ(key)).One()
// Key: "123"
// UpdatedAt: 2024-11-07 00:00:00
// State: Pending

err = dbgen.Blocks.Update(ctx, db, &dbgen.BlockSetter{
		State:       Ready,
	}, block)
```
Then I have an update hook that just updates a single column (`updated_at`),

```golang
func blocksUpdateHook(ctx context.Context, _ bob.Executor, block BlockSlice) (context.Context, error) {
	now := nowFn().UTC()
	for _, b := range block {
                // (1)
                fmt.Println("before ", b.UpdatedAt)
		b.UpdatedAt = now
                // (2)
                fmt.Println("after ", b.UpdatedAt)
	}
	return ctx, nil
}
...
// registering hooks
Blocks.BeforeUpdateHooks.Add(blockUpdateHook)
```

When the `Update` function is called I can see my `BeforeUpdateHook` running, updating the "block" rows.
at `(1)` we see the current value of the field as `2024-11-07 00:00:00` then at `(2)` as expected the field is updated to something in the future `2024-11-07 00:00:01`

At this point, I would expect the actual row to be updated with the value set in the hook, however, it seems that the value in the original `block` field gets precedence. Querying the database again proves that the updatedAt field was never updated, even though I am 100% certain the hook is being called.
```golang
block, err := dbgen.Blocks.Query(ctx, db, dbgen.SelectWhere.Blocks.Key.EQ(key)).One()
// Key: "123"
// UpdatedAt: 2024-11-07 00:00:00
// State: Ready
```

From this I conclude that the fields explicitly set on the Setter is updated correctly, however any value that is updated within the `Before/AfterUpdateHook` is overwritten by whatever is in the provided model.

**Comment by stephenafamo** [comment]
The values in the `block` itself is not used for updating. They are only used to know which primary keys to update.  
So changing their values in a hook will have no effect.

Perhaps a `BeforeUpdateSetter` hook should be added to do what you're looking for.

**Comment by iggydv** [comment]
Hi @stephenafamo!
Thanks for the reply, and I guess, it makes sense why this wasn't working.
I actually managed to get around this problem by instead using an `UpdateQueryHooks`.

Curious to know a bit more about the `BeforeUpdateSetter` I didn't see any reference to this in the docs, nor could I find this in the code tbh. How would I achieve this?

**Comment by iggydv** [comment]
We're actually trying to implement a classic ORM feature, where we trigger automatic timestamp updates on `updated_at` and `created_at` columns. I believe this is a pretty common feature in other ORMs, at least in other languages. I think this would be a really nice addition, and it means we won't need to add this logic ourselves with workarounds or use a `updateQueryHook`

**Comment by stephenafamo** [comment]
This is one of the purposedly ignored features <https://bob.stephenafamo.com/docs/code-generation/ignored-features>

I would recommend setting automatic timestamps in your database, it is fairly easy and much more reliable than doing it in the ORM. For example: https://x.com/StephenAfamO/status/1563999963851390979

**Comment by iggydv** [comment]
Indeed that is probably the cleanest way when your dealing with a small or fresh DB, unfortunately in our case we're stuck with a really big database, where migrations become quite risky, with tons of operational overhead. Having this feature would save us a lot of time and energy. 

I think there is still a valid use-case for this feature, but understand if it's not something that's widely asked for in feature requests. Perhaps it could be something to collaborate on?

**Comment by pcriv** [comment]
We went for using `UpdateQueryHooks` and `BeforeInsertHooks`.
But maybe your first proposal of having `BeforeUpdateSetter` and `BeforeInsertSetter` would be approach? In case that feature is added I mean
