### ISSUE TITLE
Table columns improvement 

### ISSUE THREAD

**Issue by hiendaovinh** [stephenafamo/bob#31]
1. The generated `UsersWhere` goes like this
```go
func UserWhere[Q psql.Filterable]() userWhere[Q] {
	return userWhere[Q]{
		ID:              psql.Where[Q, uuid.UUID](psql.Quote("users", "id")),
		Name:            psql.Where[Q, string](psql.Quote("users", "name")),
	}
}
```
Which can be shortened with `UserColumns.ID` and `UserColumns.Name`
```go
func UserWhere[Q psql.Filterable]() userWhere[Q] {
	return userWhere[Q]{
		ID:              psql.Where[Q, uuid.UUID](UserColumns.ID),
		Name:            psql.Where[Q, string](UserColumns.Name),
	}
}
```
2. `im.SetExcluded` only accept bare column names so we need another function for `psql.Expression` instead of string or a way to extract column names from psql.Quote.

**Comment by stephenafamo** [comment]
> 1\. Which can be shortened with `UserColumns.ID` and `UserColumns.Name`

This is a nice suggestions. Thank you.



> 2\. `im.SetExcluded` only accept bare column names so we need another function for `psql.Expression` instead of string or a way to extract column names from psql.Quote.

You can use `psql.Raw` to turn a raw string to an expression. But string constants are also generated. `models.ColumnNames.Users.ID` and so on.

**Comment by hiendaovinh** [comment]
2. Got it! Forgot about variables inside `bob_main.go` :smile:

**Comment by stephenafamo** [comment]
> Which can be shortened with `UserColumns.ID` and `UserColumns.Name`

I've made this change on `master`, so I'll be in the next release (I don't think I should make a release just for this 😅).
