### ISSUE TITLE
rel_load invalid memory address or nil pointer

### ISSUE THREAD

**Issue by hiendaovinh** [stephenafamo/bob#33]
In case of One() `sql.ErrNoRows`, `related` is nil and setting related.R will panic.
https://github.com/stephenafamo/bob/blob/3038260c01ba3cf1c40987c0083c461adf220bbf/gen/templates/models/10_rel_load.go.tpl#L178-L181

**Comment by hiendaovinh** [comment]
I think the correct behavior of
https://github.com/stephenafamo/bob/blob/3038260c01ba3cf1c40987c0083c461adf220bbf/gen/templates/models/10_rel_load.go.tpl#L163-L165
should be

```
if err != nil && errors.Is(err, sql.ErrNoRows) {
	return nil
}
if err != nil {
        return err
}
```

**Comment by stephenafamo** [comment]
If we imagine a situation where the relations are optional, I don't think the entire operation should throw an error if one of the relations is `nil`.

To check if the relationship was loaded the user can manually check if that relation is nil or not.

**Comment by stephenafamo** [comment]
I see what you're saying now.
Setting the reverse of the relationship panics if the relation is `nil`.

**Comment by hiendaovinh** [comment]
Sorry for my poor choice of words.
