### ISSUE TITLE
Embed structs

### ISSUE THREAD

**Issue by raphaelvigee** [stephenafamo/bob#34]
If i define the following:

```
type Flow struct {
	*models.Flow
	Model `db:"-"`
}
```

where `models` is the package generated models, and Model is a base utility that adds some Methods to my Flow structure, i m unable to Scan into it because the `internal.GetMappings` does not read embeded structs fields and only see a single column: `flow` (whic is not correct), it would be great to have it inline embeded struct fields

This method allows to use the generated models and augment them with custom business logic

**Comment by stephenafamo** [comment]
It does not read the mappings because you set the DB tag as `db:"-"`

**Comment by stephenafamo** [comment]
So, to do this, we may need to have a special DB tag to make the `GetMappings` method know what to look for.

**Comment by raphaelvigee** [comment]
Sorry I wasnt super clear, `Model` is a purely go interface stuff, must be ignored by the DB scan, hence the `-`, `*models.Flow` on the other hand contains the actual fields that need to be scanned into,

Running `internal.GetMappings`  on the `Flow` type gives out a single column (and mapper): `flow` (which maps to the embeded struct), where i expect it to list the columns contained inside the embeded struct `models.Flow`

**Comment by stephenafamo** [comment]
I'll try to think of a way to achieve this.


In the meantime, perhaps you can consider extending the templates to add shared logic that may be more elegant than embedding

**Comment by raphaelvigee** [comment]
Tbh i ve been thinking that extending the template would be a lot better, but couldnt find any details on how to do that, do you have any docs/example on how to achieve that ?

**Comment by stephenafamo** [comment]
No docs yet, but looking at the drivers themselves should help. A lot is abstracted. For example the `main` function of `bobgen-psql` is only [15 lines](https://github.com/stephenafamo/bob/blob/main/gen/bobgen-psql/main.go#LL45-L60C2).

**Comment by raphaelvigee** [comment]
So its down to making a custom gen binary similar to what ent is doing? Awesome then :) Thx for this great lib bth!

**Comment by stephenafamo** [comment]
I'm currently using a similar system to add GraphQL Relay semantics to a project of mine (Universal NodeIDs, Connections i.e. cursor pagination), hoping to release that as a standalone package soon.

A few things may change about it to be fair. I'm considering having more granular plugin hooks similar to `gqlgen`, but haven't settled on a proper implementation yet.

**Comment by stephenafamo** [comment]
> Thx for this great lib btw!

Thanks a lot 😁

**Comment by raphaelvigee** [comment]
Looking at https://github.com/stephenafamo/bob/blob/main/gen/templates/models/01_types.go.tpl, it doesnt seem to be possible to add arbitrary fields that arent columns... My `Model` binds in a bunch of structs fields (& methods)

I would suggest to implement something like wha ent is doing, its great for extensibility:
```
{{ define "model/fields/additional" }}
    {{- /* Add static fields to the "Card" entity. */}}
    {{- if eq $.Name "Card" }}
        // StaticField defined by templates.
        StaticField string `json:"static_field,omitempty"`
    {{- end }}
{{ end }}
```
ref: https://entgo.io/docs/templates/

**Comment by stephenafamo** [comment]
You're the first person (that I know of) that's using this, so the tools to add things to the templates are quite rough for now.  
Thanks for being a test subject 😀 

I will add a template block in the struct definition.

**Comment by stephenafamo** [comment]
Added a `"model/fields/additional"` block on `main`

So you should be able to do 


```
{{define "model/fields/additional"}}
  // something
{{end}}
```

**Comment by stephenafamo** [comment]
That's interesting. I'll consider implementing something similar.

**Comment by raphaelvigee** [comment]
Im trying to use `model/fields/additional`, but i m hitting two issues:
- I would need a way to add extra imports
- I would need a `model/methods/additional` (to make it conform to some interface)

**Comment by stephenafamo** [comment]
In the templates added, you can just write the methods you need. For example, in the `bobgen-graphql-relay` plugin I'm working on, I have this in a template:

```go
// IsRelayNode implements the RelayNode interface
func (o *{{$tAlias.UpSingular}}) IsRelayNode() {}
```

And it is rendered in the model. 

The setup to append the templates to the default templates goes like this:

```go
	config, driverConfig, err := helpers.GetConfigFromProvider[driver.Config](rawbytes.Provider(bobConfigFile), "psql")
	if err != nil {
		return err
	}

	d := driver.New(driverConfig)
	outputs := helpers.DefaultOutputs(d.Destination(), d.PackageName(), config.NoFactory, nil)

	// templates is embeded
	modelTemplates, err := fs.Sub(templates, "templates")
	if err != nil {
		return err
	}

	// Add our templates to the model output templates
	for _, out := range outputs {
		if out.Key != "models" {
			continue
		}
		out.Templates = append(out.Templates, ModelTemplates)
	}
```

**Comment by stephenafamo** [comment]
> So, to do this, we may need to have a special DB tag to make the `GetMappings` method know what to look for.

I've given this some thought, and I don't think it should be implemented.

It is more elegant to satisfy this use case by extending the templates, so I want to focus on making that process even smoother.

Adding logic to be able to work the same with Embedd structs will likely increase the complexity, especially regarding all the necessary mapping. This is logic that will need to be maintained indefinitely, so if there is a better way to do it (templates), I think it is best no avoid this.

The upcoming `v0.20.0` release should make extending Bob even easier, and I'll be improving documentation about using templates over the coming weeks.
