### ISSUE TITLE
malformed import path in auto-generated factory

### ISSUE THREAD

**Issue by them0ntem** [stephenafamo/bob#46]
for nested output path in bobgen config:
```
psql:
  output: pkg/models/database/testdb
```

generated factory model comes in as malformed path:
```
import models "soroco/scoutprovider/\\pkg\\models\\database\\scoutpipeline"
```

Command used to generate
```
go run github.com/stephenafamo/bob/gen/bobgen-psql@latest -c ./bobgen.yaml
```

**Comment by stephenafamo** [comment]
I assume you are running this on a Windows machine, so the paths are interpreted with backslashes and not forward slashes.

I'll fix this soon. Thanks for reporting.

**Comment by stephenafamo** [comment]
Can you try 52e50d7 and see if it is fixed? I don't have a windows machine to test with

**Comment by stephenafamo** [comment]
Going by [this CI action](https://github.com/stephenafamo/bob/actions/runs/4617517285/jobs/8163867818), it appears this issue is fixed. I've tagged a new release `v0.20.2` with the fixes.

I will close the issue now, feel free to reopen if the problem persists.

**Comment by them0ntem** [comment]
@stephenafamo tested with v0.20.2, issue is fixed. Thanks
