### ISSUE TITLE
Possibility to hook into the Update, Delete, etc methods

### ISSUE THREAD

**Issue by raphaelvigee** [stephenafamo/bob#49]
In the `Table` class i would need to be able to hook into the query of Update, Delete etc, right before `Exec` is called, to add extra conditions
Generally being able to pass extra modifier would be required

**Comment by raphaelvigee** [comment]
I believe that a similar hooks system but operating on the query would work just fine, do you see any drawback ?

**Comment by stephenafamo** [comment]
Just around the design as a whole. If another set of hooks are added then it has to be easy for a user to tell them apart. Also a decision will have to be made if the `orm.SkipHooks` should skip both model and query hooks, and if not, create an elegant mechanism of skipping, either or both set of hooks.

**Comment by raphaelvigee** [comment]
The way I see it:
These new hooks would be called `QueryHook`, also there is no need for after/before, since they would only run right before the `Exec`
`SkipHooks` could take parameters (`skipModel`, `skipQuery`) or just have different `SkipHook`s for each

**Comment by raphaelvigee** [comment]
Also on another note, it would be nice to expose the necessary tools to create an `Upsert` method, aka exposing all the `internal` functions, like `GetColumnValues` and `ToAnySlice`

**Comment by stephenafamo** [comment]
I could consider it. It's mainly internal to limit the public API so that I can make changes without breaking backwards compatibility

**Comment by stephenafamo** [comment]
Finally had some time to work on this. Try it out: b668dfd
