### ISSUE TITLE
Scan error on nullable MySQL timestamp columns while inserting

### ISSUE THREAD

**Issue by jacobmolby** [stephenafamo/bob#53]
Hi, first of all, thanks for an awesome library.

I have used the code generation on a MySQL 8.0.26 db.

We have tables with DDL like this:
```sql
CREATE TABLE `shops` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
   /* rest omitted */
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
)
```

Whenever I try to insert a time.Time value I get an error like this from the DBMS:
```
sql: Scan error on column index 15, name "created_at": unsupported Scan, storing driver.Value type []uint8 into type *time.Time
```

It happens both when I use the models to insert:
```golang
models.ShopsTable.Insert(ctx, exec, &models.ShopSetter{
   TeamID:    omit.From(uint64(1)),
   CreatedAt: omitnull.From(time.Now()),
})
```
... and when I use the factories
```golang
f.NewShop(
    factory.ShopMods.RandomizeAllColumns(nil),
    factory.ShopMods.CreatedAt(null.From(time.Now())),
).Create(ctx, exec)
```

However it does work whenever the value is set to null by me:
```golang
models.ShopsTable.Insert(ctx, exec, &models.ShopSetter{
   TeamID:    omit.From(uint64(1)),
   CreatedAt: omitnull.FromPtr[time.Time](nil),
})
```
or
```golang
f.NewShop(
   factory.ShopMods.RandomizeAllColumns(nil),
   factory.ShopMods.CreatedAt(null.FromCond(time.Now(),false)),
).Create(ctx, exec)
```

Also when using the factories and I doesn't explicit set a value I get this error:
```
Error 1292 (22007): Incorrect datetime value: '0000-00-00' for column 'created_at' at row 1
```

With code like this, where nothing is set by me:
```golang
f.NewShop(
   factory.ShopMods.RandomizeAllColumns(nil),
).Create(ctx, exec)
```

Am I doing something wrong? Or is there a bug somewhere?

I hope you can point me in the right direction :)

**Comment by stephenafamo** [comment]
The is caused by the driver. See this: <https://github.com/go-sql-driver/mysql#timetime-support>

> The default internal output type of MySQL DATE and DATETIME values is []byte which allows you to scan the value into a []byte, string or sql.RawBytes variable in your program.
>
> However, many want to scan MySQL DATE and DATETIME values into time.Time variables, which is the logical equivalent in Go to DATE and DATETIME in MySQL. You can do that by changing the internal output type from []byte to time.Time with the DSN parameter parseTime=true. You can set the default [time.Time location](https://golang.org/pkg/time/#Location) with the loc DSN parameter.

**Comment by jacobmolby** [comment]
Thanks, that did the trick 😃 Keep up the good work!

**Comment by stephenafamo** [comment]
Thank you 😁
