### ISSUE TITLE
Limit/offset should allow parameters

### ISSUE THREAD

**Issue by RangelReale** [stephenafamo/bob#63]
In SQL it is possible to use parameters for `LIMIT` and `OFFSET`, like `LIMIT $1`, but the current `Limit` function only accepts int64, maybe it should accept `any` like other functions so we could use `psql.Arg`?

**Comment by stephenafamo** [comment]
As far as I know, PostgreSQL does not allow LIMIT/OFFSET to take parameters, which is why it is implemented this way.

If you take a look at [the documentation](https://www.postgresql.org/docs/current/queries-limit.html), it says that they take a **number**.  
You can also try this out yourself.

**Comment by RangelReale** [comment]
It is used in my company's codebase, so I know it works (we use sqlx, but I don't think it would differentiate where the argument is used).

I didn't found many things in the documentation talking about positional parameters, besides a small note [here in 4.2.2](https://www.postgresql.org/docs/current/sql-expressions.html). In this chapter 7 there's no mention of parameters.

But I know it works, this comes from my production codebase using postgresql (simplified):

```sql
SELECT name FROM "user" WHERE "deleted_at" IS NULL LIMIT :limit OFFSET :offset
```

Then we use `sqlx.DB.NamedQueryContext`, which converts named parameters to db-specific parameters, $1 and $2 in this case.

**Comment by RangelReale** [comment]
I did a deep step on the code to search for special handling of LIMIT clauses in `sqlx`, `lib/pq` and `jackc/pgx`, using a simple test.

```go
rows, err := db.Query("SELECT * FROM actor OFFSET $1 LIMIT $2", 5, 10)
```

Going all the way to the network packets sent to postgres, I can see that in both postgres clients, the offset and limit are being sent as parameters, not having any special handling.

Searching their code bases for "LIMIT", there's no special handling of limit also, so I think it is safe to say that this is done at the server level.

[lib/pq](https://github.com/search?q=repo%3Alib%2Fpq%20LIMIT&type=code)

[jackc/pgx](https://github.com/search?q=repo%3Ajackc%2Fpgx%20LIMIT&type=code)

[sqlx](https://github.com/search?q=repo%3Ajmoiron%2Fsqlx%20LIMIT&type=code)

**Comment by RangelReale** [comment]
My use case on this is using prepared queries, this not being a parameter prevents me for using them.

**Comment by stephenafamo** [comment]
Just to clarify, you ran these queries against the database with the parameters for LIMIT and OFFSET and it executed correctly?

**Comment by RangelReale** [comment]
> Just to clarify, you ran these queries against the database with the parameters for LIMIT and OFFSET and it executed correctly?

Yes, I created a docker image for the sakila sample database [following this tutorial](https://daveb.medium.com/using-a-pre-seeded-postgresql-docker-image-for-faster-ci-cd-ccf35305e996), and executed this query on it.

This was using postgresql 13, in my codebase we use postgresql 11, were LIMIT with parameters also works.
