### ISSUE TITLE
There is no X ?

### ISSUE THREAD

**Issue by cemremengu** [stephenafamo/bob#67]
Thanks for your work!

Examples show usage of `X` like 

```
import "github.com/stephenafamo/bob/dialect/psql/sm"
cte := psql.Select(
    sm.From("users"),
    sm.Where(psql.X("age").GTE(21)),
)
```

However, `X` does not seem to exist as part of `psql`. Am I doing something wrong or docs are outdated?

**Comment by stephenafamo** [comment]
The `X` starter was removed in `v0.18.0`. <https://github.com/stephenafamo/bob/releases/tag/v0.18.0>.

I will update the docs to reflect this.
