### ISSUE TITLE
ORM generation not working as per README.md

### ISSUE THREAD

**Issue by daddz** [stephenafamo/bob#7]
First of all thanks for this library. Looks really cool and I'm eager to play around more with it!

When trying to generate the ORM the readme says to use:
```
DSN=postgres://user:pass@host:port/dbname go run github.com/go-bob/bobgen-psql@latest
```
but that doesn't work and results in:
```
Error: database dsn is not set
exit status 1
```
I got it to work with:
```
PSQL_DSN=postgres://user:pass@host:port/dbname go run github.com/go-bob/bobgen-psql@latest
```
Edit:
It works correctly with the config file, there was an error on my side.
~~I also tried to use the yaml to set the DSN but that didn't get picked up at all:~~
```
psql:
  dsn: postgres://user:pass@host:port/dbname
```
~~Same error here:~~
```
Error: database dsn is not set
exit status 1
```

**Comment by stephenafamo** [comment]
Thanks. I'll update the README.
