### ISSUE TITLE
Different hooks for One and Many operations

### ISSUE THREAD

**Issue by inoc603** [stephenafamo/bob#74]
I noticed that bob uses the same hook for both One and Many operations. Like here in `AfterUpdateHook`:

https://github.com/stephenafamo/bob/blob/4824718378d4e83558ecb8f5ff7a1f94a4bf1d99/dialect/mysql/table.go#L296-L301

I think it might be desirable in quite some cases to handle all rows Updated/Deleted/Inserted together, e.g. update another table in batch, record the number of rows into some kind of metrics. And passing an executor to a function in a loop might lead to unexpected performance pitfalls.

Maybe we can have something like `AfterUpdateManyHook`, `AfterUpdateOneHook` ? It's likely easy to implement but keeping backward compatibility is quite tricky.

A not very elegant way I can think of is abusing the context parameter. Add a pairs of functions
- `orm.RequestBatchHook(context.Context) context.Context` 
- `orm.BatchHookRequested(context.Context) bool`. 

The user who wanted to handle hooks in batch adds an `AfterUpdateHook` in which `orm.RequestBatchHook` is called. Then add their hook function that handles multiple rows in an `AfterUpdateManyHook`.

In corresponding methods in `Table`, `AfterUpdateManyHook` is used if requested.

```go
	for i, row := range rows {
		ctx, err = t.AfterUpdateHooks.Do(ctx, exec, row)
		if err != nil {
			return 0, err
		}
                 if orm.BatchHookRequested(ctx) && i == 0 {
                         if _, err := t.AfterUpdateManyHooks.Do(ctx, exec, rows); err != nil {
                                 return 0, err
                         }
                         break
                 }
	}
```

Though I'm not quite sure if it's worth adding this complexity. What can be done by hooks can always be done manually without hooks. Any suggestions ?

**Comment by stephenafamo** [comment]
I'm not sure about this at all.

This is also fairly easy to do manually
* Create a context key for your batch operation
* Set the context key to `true` before the batch operation
* Check for the context key in the hook and skip if it isn't `true`
* Once the hook operation is performed successfully, update the context value to `false` so that other object of the loop are skipped.

**Comment by inoc603** [comment]
If the hook function still takes one row each time, for a btach operation I would have to store all the rows somewhere, and I also don't see any way that the function can tell it's the last row in a batch.

**Comment by inoc603** [comment]
> If the hook function still takes one row each time, for a btach operation I would have to store all the rows somewhere, and I also don't see any way that the function can tell if it's the last row in a batch.

Oh, manually adding the number of rows and something like a "query id" to the context could solve the "last row" problem. But I still have to append each row to a slice labeled by the "query id" though.

**Comment by stephenafamo** [comment]
> Sorry I made a mistake in the code example. the `AfterUpdateManyHooks` takes a slice of rows as arguments. It would be of type `orm.Hook[[]T]`.

Wouldn't it then be easier to do it outside the loop?

> Oh, manually adding the number of rows and something like a "query id" to the context could solve the "last row" problem. But I still have to append each row to a slice labeled by the "query id" though.

Yeah, it wouldn't be pretty 🤔 .  
I'm not sure how best to do this without making things even more complex

**Comment by stephenafamo** [comment]
> So `BatachedAfterUpdateHooks` would work almost the same as `AfterUpdateHooks`, with the only difference being it takes all the rows at once.

I'm just a bit hesitant to introduce another hook. I would need to think about this for a while.

**Comment by stephenafamo** [comment]
Actually, the solution would be to convert the existing hooks to take a slice of the objects instead.  
That way, if someone wanted to operate on them individually, the can do a loop in the hook.
