### ISSUE TITLE
How to compose generated Wheres

### ISSUE THREAD

**Issue by inoc603** [stephenafamo/bob#77]
The generated wheres, e.g. `models.SelectWhere.Video.ID.EQ(1)`  returns `bob.Mod[Q]` which is not an `bob.Expression`. I can't find a way to compose these mods like this:

```go
Or(
  models.SelectWhere.Video.ID.EQ(1),
  models.SelectWhere.Video.SponsorID.EQ(2),
)
```

I noticed that `WhereMod` has a  private `Expression` field, maybe we can make it implements the `Expression` interface? But I don't have any clear idea what the final api should be like. Any thoughts?

**Comment by stephenafamo** [comment]
I see how this would be convenient, but it isn't so straightforward because of the existing design. Let me think through it a bit.

**Comment by stephenafamo** [comment]
Take a look at #87 for a possible implementation.
