### ISSUE TITLE
Generated ORM is too opinionated about import path

### ISSUE THREAD

**Issue by plunkettscott** [stephenafamo/bob#8]
The generated ORM seems pretty opinionated about where it wants to be placed inside of the go module. Specifically, the `factory` package attempts to access the `models` package at `module/models` where `module` is the name of the module specified in `go.mod`.

For example, if my module was called `app`, the `factory` package would attempt to access the `models` from `app/models`, which is not the case where we're using it. I had to disable factories altogether due to this.

Is there any way we can introduce a config option for the generator to configure things like the `models` package's import path?

**Comment by stephenafamo** [comment]
Are you manually moving the generated models to a different folder?  
It is supposed to combine the set output path of the models and the module root to figure out the models import path.

For example, if you're using the `psql` driver and have configuration that looks like this


```yaml
psql:
  output: store/models
```

Then factory will be generated at `module/root/store/models/factory` and look for the models package at `module/root/store/models`.

**Comment by plunkettscott** [comment]
Ah, I missed that `psql.output` was even a thing. My bad. I am not moving anything, though, I'm just using `//go:generate` within the directory I wanted `models` to be placed.

**Comment by stephenafamo** [comment]
🤔 this is interesting. 
There is an assumption that `//go:generate` is run from the root of the module.

I'll see if I can make it also detect the `$PWD` and know where it is being run in relation to the module, in the meantime, it would be best to just run `go generate` from the root

**Comment by plunkettscott** [comment]
To clarify, I am running `go generate` from the root, but the `//go:generate` statement is not at the root (and other tools handle this correctly).

**Comment by stephenafamo** [comment]
This should work properly in `v0.15.4`
