### ISSUE TITLE
PostgreSQL query builder .In() only generates ($1) when using slice

### ISSUE THREAD

**Issue by raspi** [stephenafamo/bob#82]
Hi,

I'm trying this library and found an issue with `WHERE x IN (...)`.

```go
q := psql.Select(
  sm.Columns(`id`, `movie_id`, `author_id`, `title`, `published`),
  sm.From(`posts`),
  sm.Where(psql.Quote(`date_deleted`).IsNull()),
  sm.OrderBy(`published DESC`),
)
```

So I wanted to add `WHERE movie_id IN (...)` but currently `.In` only generates `($1)` if you give it for example `[]uint64`

```go
// Filter: Movie ID(s)
if len(filter.MovieIds) > 0 {
	q.Apply(sm.Where(psql.Quote(`movie_id`).In(
		filter.MovieIds,
	)))
}
```

Because `filter.MovieIds` contained multiple values and only `IN ($1)` was generated so the generated query failed.

So I ended up with a wrapper that fixes the problem:

```go
// Filter: Movie ID(s)
if len(filter.MovieIds) > 0 {
	q.Apply(sm.Where(psql.Quote(`movie_id`).In(
		genPGArgs(filter.MovieIds)...,
	)))
}
```

And the wrapper:

```go
func genPGArgs[T any](src []T) (args []bob.Expression) {
	for _, i := range src {
		args = append(args, psql.Arg(i))
	}
	return args
}
```

This generates now the `IN ($1, $2, ... $N)` correctly.

Is this the proper way?

I'd like to see an example in the [PostgreSQL query building docs](https://bob.stephenafamo.com/docs/query-builder/psql/examples/select) for this use case when using a slice.

**Comment by stephenafamo** [comment]
Slices are not automatically converted to a list of args since there may be situations where the user wants to pass a slice as a single argument.

What you have done works, you can also pass a list of values to `Arg` directly, you may have to first convert it from `[]uint` to `[]any`. In Bob's internal package, I actually have a generic function to do this:


```go
func ToAnySlice[T any, Ts ~[]T](slice Ts) []any {
	ret := make([]any, len(slice))
	for i, val := range slice {
		ret[i] = val
	}

	return ret
}
```

```go
if len(filter.MovieIds) > 0 {
	q.Apply(sm.Where(psql.Quote(`movie_id`).In(
		psql.Arg(ToAnySlice(filter.MovieIds)...),
	)))
}
```
