### ISSUE TITLE
`uuid` package in-use is different from most other package's

### ISSUE THREAD

**Issue by plunkettscott** [stephenafamo/bob#9]
The `github.com/gofrs/uuid` package is not the standard used in most other packages, so it's requiring us to translate between the two. In a few places, this is fine, but as we expand the use of `bob` this might be annoying. I tried to customize the `uuid` type using the replacements config, but then both `uuid` packages were imported unnecessarily.

There should probably be a config item for the uuid package that could default to the `gofrs` package. If that's not possible, honoring the `uuid` type's package and only using that would be just as well.

**Comment by stephenafamo** [comment]
I assume this means you're using the psql driver right? I'll add a configuration to set the UUID package to use

**Comment by plunkettscott** [comment]
Yep, using the psql driver.

**Comment by stephenafamo** [comment]
Fixed in [this commit](https://github.com/stephenafamo/bob/commit/d3ec475db794b23b72d5fc9ebefb7e9162aae2e4). Tagged `v0.15.3`

You can now configure it with

```yaml
psql:
  uuid_pkg: google
```
